/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package proyectofinalpoog3;

/**
 *
 * @author Dueli
 */


public class FormularioGeneralUpdate extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormularioGeneralUpdate.class.getName());

    // ── Backend ──────────────────────────────────────────────
    private GestionDeProductos gestion = new GestionDeProductos();
    private java.util.ArrayList<Cliente> clientes = new java.util.ArrayList<>();
    private ReportesDeVentas reportes = new ReportesDeVentas();
    private Cliente clienteActual = null;
    private javax.swing.table.DefaultTableModel modeloCarrito;

    /**
     * Creates new form FormularioGeneralUpdate
     */
    public FormularioGeneralUpdate() {
        initComponents();
        modeloCarrito = (javax.swing.table.DefaultTableModel) tablaCarrito.getModel();
        modeloCarrito.setRowCount(0);  // ← AGREGA ESTA LÍNEA: limpia filas fantasma
        configurarSeleccionTabla();
        actualizarTablaInventario();
        actualizarComboProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaInvetario = new javax.swing.JTable();
        panelRegistrar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboCategoriaReg = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtRegId = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtRegNombre = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtRegMarca = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtRegModelo = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtRegColor = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtRegStock = new javax.swing.JTextPane();
        jLabel8 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        jScrollPane16 = new javax.swing.JScrollPane();
        txtRegPrecio = new javax.swing.JTextPane();
        jLabel17 = new javax.swing.JLabel();
        panelRegistrar1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtModId = new javax.swing.JTextPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtModNombre = new javax.swing.JTextPane();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        txtModMarca = new javax.swing.JTextPane();
        jScrollPane12 = new javax.swing.JScrollPane();
        txtModModelo1 = new javax.swing.JTextPane();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        txtModColor1 = new javax.swing.JTextPane();
        jLabel14 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane15 = new javax.swing.JScrollPane();
        textModPrecio = new javax.swing.JTextPane();
        jPanel2 = new javax.swing.JPanel();
        panelCliente = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtCliEdad = new javax.swing.JTextField();
        txtCliNombre = new javax.swing.JTextField();
        txtCliDni = new javax.swing.JTextField();
        txtCliTelefono = new javax.swing.JTextField();
        btnRegistrarCliente = new javax.swing.JButton();
        panelCliente1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        comboProductos = new javax.swing.JComboBox<>();
        txtCantidad = new javax.swing.JTextField();
        btnAgregarProducto = new javax.swing.JButton();
        panelCliente2 = new javax.swing.JPanel();
        lblCliEdad = new javax.swing.JLabel();
        lblCliNombre = new javax.swing.JLabel();
        lblCliDni = new javax.swing.JLabel();
        lblCliTelefono = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        btnGenerarBoleta = new javax.swing.JButton();
        btnQuitarProducto = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        tablaCarrito = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaInvetario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Precio (S/) ", "Stock", "Tipo"
            }
        ));
        jScrollPane1.setViewportView(tablaInvetario);

        panelRegistrar.setBorder(javax.swing.BorderFactory.createTitledBorder("Registrar nuevo producto"));

        jLabel1.setText("Categoría:");

        comboCategoriaReg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Electrónico", "Alimento", "Accesorio" }));
        comboCategoriaReg.addActionListener(this::comboCategoriaRegActionPerformed);

        jLabel2.setText("ID producto:");

        jScrollPane2.setViewportView(txtRegId);

        jScrollPane3.setViewportView(txtRegNombre);

        jLabel3.setText("Nombre:");

        jLabel4.setText("Marca:");

        jScrollPane4.setViewportView(txtRegMarca);

        jScrollPane5.setViewportView(txtRegModelo);

        jLabel5.setText("Modelo:");

        jScrollPane6.setViewportView(txtRegColor);

        jLabel6.setText("Color:");

        jScrollPane8.setViewportView(txtRegStock);

        jLabel8.setText("Stock:");

        btnRegistrar.setBackground(new java.awt.Color(102, 204, 255));
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar nuevo producto");
        btnRegistrar.addActionListener(this::btnRegistrarActionPerformed);

        jScrollPane16.setViewportView(txtRegPrecio);

        jLabel17.setText("Precio (S/)");

        javax.swing.GroupLayout panelRegistrarLayout = new javax.swing.GroupLayout(panelRegistrar);
        panelRegistrar.setLayout(panelRegistrarLayout);
        panelRegistrarLayout.setHorizontalGroup(
            panelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegistrarLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(panelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelRegistrarLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelRegistrarLayout.createSequentialGroup()
                        .addGroup(panelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(panelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboCategoriaReg, 0, 122, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane5)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane8))))
                .addGap(44, 44, 44))
        );
        panelRegistrarLayout.setVerticalGroup(
            panelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistrarLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(panelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboCategoriaReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelRegistrarLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelRegistrarLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        panelRegistrar1.setBorder(javax.swing.BorderFactory.createTitledBorder("Modificar producto"));

        jLabel10.setText("ID ( INMUTABLE):");

        txtModId.setEnabled(false);
        txtModId.setVerifyInputWhenFocusTarget(false);
        jScrollPane9.setViewportView(txtModId);

        jScrollPane10.setViewportView(txtModNombre);

        jLabel11.setText("Nombre:");

        jLabel12.setText("Marca:");

        jScrollPane11.setViewportView(txtModMarca);

        jScrollPane12.setViewportView(txtModModelo1);

        jLabel13.setText("Modelo:");

        jScrollPane13.setViewportView(txtModColor1);

        jLabel14.setText("Color:");

        btnModificar.setBackground(new java.awt.Color(255, 153, 51));
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("Modificar Producto Seleccionado");
        btnModificar.addActionListener(this::btnModificarActionPerformed);

        jLabel7.setText("Selecciona un producto en la tabla para editar");

        jLabel16.setText("Precio (S/)");

        jScrollPane15.setViewportView(textModPrecio);

        javax.swing.GroupLayout panelRegistrar1Layout = new javax.swing.GroupLayout(panelRegistrar1);
        panelRegistrar1.setLayout(panelRegistrar1Layout);
        panelRegistrar1Layout.setHorizontalGroup(
            panelRegistrar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegistrar1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(panelRegistrar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelRegistrar1Layout.createSequentialGroup()
                        .addGroup(panelRegistrar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelRegistrar1Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelRegistrar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane9)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane12)
                            .addComponent(jScrollPane13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))))
                .addGap(44, 44, 44))
        );
        panelRegistrar1Layout.setVerticalGroup(
            panelRegistrar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistrar1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRegistrar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane9)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRegistrar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane10)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRegistrar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelRegistrar1Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelRegistrar1Layout.createSequentialGroup()
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelRegistrar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane13)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRegistrar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panelRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(panelRegistrar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRegistrar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Gestión de Inventario", jPanel1);

        panelCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setFont(new java.awt.Font("Harrington", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Datos del cliente");
        jLabel9.setToolTipText("");

        jLabel15.setText("Nombre:");

        jLabel18.setText("Edad:");

        jLabel19.setText("DNI:");

        jLabel20.setText("Telefono:");

        txtCliEdad.addActionListener(this::txtCliEdadActionPerformed);

        txtCliNombre.addActionListener(this::txtCliNombreActionPerformed);

        txtCliDni.addActionListener(this::txtCliDniActionPerformed);

        txtCliTelefono.addActionListener(this::txtCliTelefonoActionPerformed);

        btnRegistrarCliente.setText("Registrar cliente");
        btnRegistrarCliente.addActionListener(this::btnRegistrarClienteActionPerformed);

        javax.swing.GroupLayout panelClienteLayout = new javax.swing.GroupLayout(panelCliente);
        panelCliente.setLayout(panelClienteLayout);
        panelClienteLayout.setHorizontalGroup(
            panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClienteLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelClienteLayout.createSequentialGroup()
                        .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel15)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addGap(35, 35, 35)
                        .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCliNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(txtCliEdad)
                            .addComponent(txtCliDni)
                            .addComponent(txtCliTelefono)))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelClienteLayout.setVerticalGroup(
            panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClienteLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel9)
                .addGap(26, 26, 26)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtCliNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtCliEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(txtCliDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtCliTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRegistrarCliente)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        panelCliente1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel21.setFont(new java.awt.Font("Harrington", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Añadir producto al carrito  ");

        jLabel22.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel22.setText("Producto:");

        jLabel23.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel23.setText("Cantidad:");

        txtCantidad.addActionListener(this::txtCantidadActionPerformed);

        btnAgregarProducto.setBackground(new java.awt.Color(51, 102, 0));
        btnAgregarProducto.setText("Añadir producto");
        btnAgregarProducto.addActionListener(this::btnAgregarProductoActionPerformed);

        javax.swing.GroupLayout panelCliente1Layout = new javax.swing.GroupLayout(panelCliente1);
        panelCliente1.setLayout(panelCliente1Layout);
        panelCliente1Layout.setHorizontalGroup(
            panelCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCliente1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelCliente1Layout.createSequentialGroup()
                        .addGroup(panelCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addGap(55, 55, 55)
                        .addGroup(panelCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboProductos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelCliente1Layout.createSequentialGroup()
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(btnAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        panelCliente1Layout.setVerticalGroup(
            panelCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCliente1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(panelCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(btnAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelCliente2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblCliEdad.setText("Edad: ---");

        lblCliNombre.setText("Nombre cliente: ---");

        lblCliDni.setText("DNI: ---");

        lblCliTelefono.setText("Teléfono: ---");

        jLabel24.setFont(new java.awt.Font("Harrington", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel24.setText("Generación de boleta");
        jLabel24.setToolTipText("");

        btnGenerarBoleta.setBackground(new java.awt.Color(0, 102, 51));
        btnGenerarBoleta.setText("Generar boleta");
        btnGenerarBoleta.addActionListener(this::btnGenerarBoletaActionPerformed);

        btnQuitarProducto.setText("Quitar producto");
        btnQuitarProducto.addActionListener(this::btnQuitarProductoActionPerformed);

        tablaCarrito.setBackground(new java.awt.Color(51, 51, 51));
        tablaCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Cant.", "P.unit", "Subtotal"
            }
        ));
        jScrollPane7.setViewportView(tablaCarrito);

        javax.swing.GroupLayout panelCliente2Layout = new javax.swing.GroupLayout(panelCliente2);
        panelCliente2.setLayout(panelCliente2Layout);
        panelCliente2Layout.setHorizontalGroup(
            panelCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCliente2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCliente2Layout.createSequentialGroup()
                        .addGroup(panelCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCliEdad)
                            .addComponent(lblCliNombre)
                            .addComponent(lblCliDni)
                            .addComponent(lblCliTelefono))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelCliente2Layout.createSequentialGroup()
                        .addGroup(panelCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(panelCliente2Layout.createSequentialGroup()
                                .addGap(0, 106, Short.MAX_VALUE)
                                .addComponent(btnQuitarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnGenerarBoleta, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23))))
        );
        panelCliente2Layout.setVerticalGroup(
            panelCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCliente2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel24)
                .addGap(26, 26, 26)
                .addComponent(lblCliNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCliEdad)
                .addGap(18, 18, 18)
                .addComponent(lblCliDni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCliTelefono)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addGroup(panelCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerarBoleta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuitarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCliente1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCliente2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelCliente2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(panelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52))
        );

        jTabbedPane2.addTab("Compra de Productos", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.getAccessibleContext().setAccessibleName("JTabbedPane2");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void comboCategoriaRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCategoriaRegActionPerformed
        // No necesita lógica aquí, se lee el valor al presionar "Registrar"
    }//GEN-LAST:event_comboCategoriaRegActionPerformed

    private void txtCliEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCliEdadActionPerformed
        // No se usa
    }//GEN-LAST:event_txtCliEdadActionPerformed

    private void txtCliNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCliNombreActionPerformed
        // No se usa
    }//GEN-LAST:event_txtCliNombreActionPerformed

    private void txtCliDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCliDniActionPerformed
        // No se usa
    }//GEN-LAST:event_txtCliDniActionPerformed

    private void txtCliTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCliTelefonoActionPerformed
        // No se usa
    }//GEN-LAST:event_txtCliTelefonoActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // No se usa
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
        agregarProductoAlCarrito();
    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    private void btnRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarClienteActionPerformed
        registrarCliente();
    }//GEN-LAST:event_btnRegistrarClienteActionPerformed

    private void btnQuitarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarProductoActionPerformed
        int fila = tablaCarrito.getSelectedRow();
        if (fila >= 0) {
            // Devolver el stock al inventario antes de quitar la fila
            String idProducto = String.valueOf(modeloCarrito.getValueAt(fila, 0));
            int cantidad = Integer.parseInt(String.valueOf(modeloCarrito.getValueAt(fila, 2)));
            Producto p = gestion.buscarPorId(idProducto);
            if (p != null) {
                p.setStock(p.getStock() + cantidad);
            }
            modeloCarrito.removeRow(fila);
            actualizarTablaInventario();
            actualizarComboProductos();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Selecciona un producto del carrito primero.");
        }
    }//GEN-LAST:event_btnQuitarProductoActionPerformed

    private void btnGenerarBoletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarBoletaActionPerformed
        generarBoleta();
    }//GEN-LAST:event_btnGenerarBoletaActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        modificarProducto(txtModId.getText().trim());
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        registrarProducto();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    // ═══════════════════════════════════════════════════════════════════
    // MÉTODOS DE LÓGICA DE NEGOCIO (escritos a mano, no tocados por el diseñador)
    // ═══════════════════════════════════════════════════════════════════

    /** Configura el listener de selección de la tabla de inventario. */
    private void configurarSeleccionTabla() {
        tablaInvetario.getSelectionModel().addListSelectionListener(ev -> {
            if (ev.getValueIsAdjusting()) return;
            int fila = tablaInvetario.getSelectedRow();
            if (fila < 0) return;
            txtModId.setText(String.valueOf(tablaInvetario.getValueAt(fila, 0)));
            txtModNombre.setText(String.valueOf(tablaInvetario.getValueAt(fila, 1)));
            textModPrecio.setText(String.valueOf(tablaInvetario.getValueAt(fila, 2)));
        });
    }

    /** Registra un producto nuevo en el inventario. */
    private void registrarProducto() {
        String id     = txtRegId.getText().trim();
        String nombre = txtRegNombre.getText().trim();
        String marca  = txtRegMarca.getText().trim();
        String modelo = txtRegModelo.getText().trim();
        String color  = txtRegColor.getText().trim();
        String precioTxt = txtRegPrecio.getText().trim();
        String stockTxt  = txtRegStock.getText().trim();
        String tipo   = (String) comboCategoriaReg.getSelectedItem();

        if (id.isEmpty() || nombre.isEmpty() || precioTxt.isEmpty() || stockTxt.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "ID, Nombre, Precio y Stock son obligatorios.", "Aviso",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        double precio;
        int stock;
        try {
            precio = Double.parseDouble(precioTxt);
            stock  = Integer.parseInt(stockTxt);
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Precio y Stock deben ser números válidos.", "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (precio <= 0 || stock < 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Precio debe ser mayor a 0 y Stock no puede ser negativo.", "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        Producto prod;
        switch (tipo) {
            case "Electrónico":
                prod = new proyectofinalpoog3.Productos.ProductoElectronico(
                    id, nombre, precio, stock, 12, marca);
                break;
            case "Accesorio":
                prod = new proyectofinalpoog3.Productos.ProductoAccesorio(
                    id, nombre, precio, stock, marca, color);
                break;
            default: // Alimento
                prod = new proyectofinalpoog3.Productos.ProductoAlimento(
                    id, nombre, precio, stock, "—", false);
                break;
        }

        boolean agregado = gestion.agregarProducto(prod);

        if (!agregado) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "❌ Ya existe un producto con el ID: " + id + "\nUsa un ID diferente.",
            "ID duplicado",
            javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

        actualizarTablaInventario();
        actualizarComboProductos();

        txtRegId.setText(""); txtRegNombre.setText(""); txtRegMarca.setText("");
        txtRegModelo.setText(""); txtRegColor.setText("");
        txtRegPrecio.setText(""); txtRegStock.setText("");

        javax.swing.JOptionPane.showMessageDialog(this,
            "✔ Producto registrado: " + nombre, "Éxito",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }

    /** Modifica el producto cuyo ID se pasa como parámetro. */
    private void modificarProducto(String id) {
        if (id.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Primero selecciona un producto en la tabla.", "Aviso",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        String nuevoNombre = txtModNombre.getText().trim();
        String nuevoPrecioTxt = textModPrecio.getText().trim();

        if (nuevoNombre.isEmpty() || nuevoPrecioTxt.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Nombre y Precio no pueden estar vacíos.", "Aviso",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        double nuevoPrecio;
        try {
            nuevoPrecio = Double.parseDouble(nuevoPrecioTxt);
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "El precio debe ser un número válido.", "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        gestion.editarProducto(id, nuevoNombre, nuevoPrecio);
        actualizarTablaInventario();
        actualizarComboProductos();

        txtModNombre.setText(""); txtModMarca.setText("");
        txtModModelo1.setText(""); txtModColor1.setText(""); textModPrecio.setText("");

        javax.swing.JOptionPane.showMessageDialog(this,
            "✔ Producto actualizado.", "Éxito",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }

    /** Recarga la tabla de inventario desde GestionDeProductos. */
    private void actualizarTablaInventario() {
        javax.swing.table.DefaultTableModel modelo =
            (javax.swing.table.DefaultTableModel) tablaInvetario.getModel();
        modelo.setRowCount(0);
        for (Producto p : gestion.getInventario()) {
            modelo.addRow(new Object[]{
                p.getId(),
                p.getNombre(),
                String.format("%.2f", p.getPrecio()),
                p.getStock(),
                p.getClass().getSimpleName().replace("Producto", "")
            });
        }
    }

    /** Registra el cliente actual. */
    private void registrarCliente() {
        String nombre   = txtCliNombre.getText().trim();
        String edadTxt  = txtCliEdad.getText().trim();
        String dniTxt   = txtCliDni.getText().trim();
        String telefono = txtCliTelefono.getText().trim();

        if (nombre.isEmpty() || edadTxt.isEmpty() || dniTxt.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Nombre, Edad y DNI son obligatorios.", "Aviso",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int edad, dni;
        try {
            edad = Integer.parseInt(edadTxt);
            dni  = Integer.parseInt(dniTxt);
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Edad y DNI deben ser números.", "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (edad < 18) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "El cliente debe ser mayor de 18 años.", "Aviso",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        clienteActual = new Cliente(dni, nombre, edad, telefono);
        clientes.add(clienteActual);

        lblCliNombre.setText("Nombre cliente: " + clienteActual.getNombre());
        lblCliEdad.setText("Edad: " + clienteActual.getEdad());
        lblCliDni.setText("DNI: " + clienteActual.getDni());
        lblCliTelefono.setText("Teléfono: " + clienteActual.getTelefono());

        txtCliNombre.setText(""); txtCliEdad.setText("");
        txtCliDni.setText(""); txtCliTelefono.setText("");

        javax.swing.JOptionPane.showMessageDialog(this,
            "✔ Cliente registrado: " + nombre, "Éxito",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }

    /** Agrega el producto seleccionado en el combo al carrito. */
    private void agregarProductoAlCarrito() {
        if (clienteActual == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Primero registra un cliente.", "Aviso",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        String seleccion = (String) comboProductos.getSelectedItem();
        if (seleccion == null || seleccion.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "No hay productos en el inventario.", "Aviso",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        String idProducto = seleccion.split(" — ")[0].trim();
        Producto prod = gestion.buscarPorId(idProducto);

        if (prod == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Producto no encontrado.", "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        int cantidad;
        try {
            cantidad = Integer.parseInt(txtCantidad.getText().trim());
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "La cantidad debe ser un número.", "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (cantidad <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "La cantidad debe ser mayor a 0.", "Aviso",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (prod.getStock() < cantidad) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Stock insuficiente. Disponible: " + prod.getStock(), "Aviso",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        double subtotal = prod.getPrecio() * cantidad;
        prod.reducirStock(cantidad);

        modeloCarrito.addRow(new Object[]{
            prod.getId(),
            prod.getNombre(),
            cantidad,
            String.format("%.2f", prod.getPrecio()),
            String.format("%.2f", subtotal)
        });

        actualizarTablaInventario();
        txtCantidad.setText("1");
    }

    /** Genera la boleta de venta con todos los productos del carrito. */
    private void generarBoleta() {
        if (clienteActual == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Registra un cliente primero.", "Aviso",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (modeloCarrito.getRowCount() == 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "El carrito está vacío.", "Aviso",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        StringBuilder sb = new StringBuilder();
        sb.append("════════════════════════════════════════\n");
        sb.append("        MINIMARKET — BOLETA DE VENTA    \n");
        sb.append("════════════════════════════════════════\n");
        sb.append(String.format("Cliente : %s%n", clienteActual.getNombre()));
        sb.append(String.format("DNI     : %d%n", clienteActual.getDni()));
        sb.append(String.format("Tel     : %s%n", clienteActual.getTelefono()));
        sb.append("────────────────────────────────────────\n");
        sb.append(String.format("%-20s %5s %10s%n", "Producto", "Cant.", "Subtotal"));
        sb.append("────────────────────────────────────────\n");

        double total = 0;
        for (int i = 0; i < modeloCarrito.getRowCount(); i++) {
            String nombre   = String.valueOf(modeloCarrito.getValueAt(i, 1));
            int    cantidad = Integer.parseInt(String.valueOf(modeloCarrito.getValueAt(i, 2)));
            double subtotal = Double.parseDouble(
                String.valueOf(modeloCarrito.getValueAt(i, 4)));
            sb.append(String.format("%-20s %5d   S/ %6.2f%n", nombre, cantidad, subtotal));
            total += subtotal;
        }

        sb.append("────────────────────────────────────────\n");
        sb.append(String.format("TOTAL           :      S/ %6.2f%n", total));
        sb.append("════════════════════════════════════════\n");

        CompraDeProductos compra = new CompraDeProductos(clienteActual);
        for (int i = 0; i < modeloCarrito.getRowCount(); i++) {
            String idProd = String.valueOf(modeloCarrito.getValueAt(i, 0));
            Producto p = gestion.buscarPorId(idProd);
            if (p != null) {
                int cant = Integer.parseInt(String.valueOf(modeloCarrito.getValueAt(i, 2)));
                compra.getLineas().add(new CompraDeProductos.LineaDeCompra(p, cant));
            }
        }
        reportes.registrarVenta(compra);

        javax.swing.JTextArea areaTexto = new javax.swing.JTextArea(sb.toString());
        areaTexto.setEditable(false);
        areaTexto.setFont(new java.awt.Font(java.awt.Font.MONOSPACED, java.awt.Font.PLAIN, 13));
        javax.swing.JScrollPane scrollBoleta = new javax.swing.JScrollPane(areaTexto);
        scrollBoleta.setPreferredSize(new java.awt.Dimension(440, 320));

        javax.swing.JOptionPane.showMessageDialog(this, scrollBoleta,
            "Boleta de Venta #" + compra.getIdCompra(),
            javax.swing.JOptionPane.INFORMATION_MESSAGE);

        modeloCarrito.setRowCount(0);
        clienteActual = null;
        lblCliNombre.setText("Nombre cliente: ---");
        lblCliEdad.setText("Edad: ---");
        lblCliDni.setText("DNI: ---");
        lblCliTelefono.setText("Teléfono: ---");
    }

    /** Actualiza el JComboBox de productos con el inventario actual. */
    private void actualizarComboProductos() {
        comboProductos.removeAllItems();
        for (Producto p : gestion.getInventario()) {
            comboProductos.addItem(String.format("%s — %s (S/ %.2f)",
                p.getId(), p.getNombre(), p.getPrecio()));
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormularioGeneralUpdate().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnGenerarBoleta;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnQuitarProducto;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegistrarCliente;
    private javax.swing.JComboBox<String> comboCategoriaReg;
    private javax.swing.JComboBox<String> comboProductos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lblCliDni;
    private javax.swing.JLabel lblCliEdad;
    private javax.swing.JLabel lblCliNombre;
    private javax.swing.JLabel lblCliTelefono;
    private javax.swing.JPanel panelCliente;
    private javax.swing.JPanel panelCliente1;
    private javax.swing.JPanel panelCliente2;
    private javax.swing.JPanel panelRegistrar;
    private javax.swing.JPanel panelRegistrar1;
    private javax.swing.JTable tablaCarrito;
    private javax.swing.JTable tablaInvetario;
    private javax.swing.JTextPane textModPrecio;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCliDni;
    private javax.swing.JTextField txtCliEdad;
    private javax.swing.JTextField txtCliNombre;
    private javax.swing.JTextField txtCliTelefono;
    private javax.swing.JTextPane txtModColor1;
    private javax.swing.JTextPane txtModId;
    private javax.swing.JTextPane txtModMarca;
    private javax.swing.JTextPane txtModModelo1;
    private javax.swing.JTextPane txtModNombre;
    private javax.swing.JTextPane txtRegColor;
    private javax.swing.JTextPane txtRegId;
    private javax.swing.JTextPane txtRegMarca;
    private javax.swing.JTextPane txtRegModelo;
    private javax.swing.JTextPane txtRegNombre;
    private javax.swing.JTextPane txtRegPrecio;
    private javax.swing.JTextPane txtRegStock;
    // End of variables declaration//GEN-END:variables
}
